services:
  # Base de datos
  database:
    image: postgres:16-alpine
    container_name: taskflow_db_dev
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow_user
      POSTGRESS_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - taskflow_network

  backend:
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
    container_name: taskflow_backend_dev
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: taskflow
      DB_USERNAME: taskflow_user
      DB_PASSWORD: secret
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
    networks:
      - taskflow_network

  # frontend:
  #   build:
  #     context: contextPath
  #     dockerfile: Dockerfile

volumes:
  postgres_data_dev:

networks:
  taskflow_network: